changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - octocat
  categories:
    - title: Breaking Changes 🛠
      labels:
        - major
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - minor
        - enhancement
    - title: Bug Fixes 🐞
      labels:
        - patch
        - bug
    - title: Other Changes
      labels:
        - "*"
